defaultContentLanguage = 'fr'
defaultContentLanguageInSubdir = false
baseURL = "https://karl-karas.github.io/imperatorpictures/"
languageCode = "fr-fr"
title = "Imperator Pictures"
theme = "ananke"

environment = "production"

[imaging]
  resampleFilter = "catmullrom"
  quality = 75
  anchor = "smart"

[params]
  env = "production"
  subtitle = "Une association artistique de création cinématographique"

[cascade]
  featured_image = 'images/banner.jpg'

SectionPagesMenu = "main"
Paginate = 3 
enableRobotsTXT = true
[languages]
  [languages.fr]
    languageName = "Français"
    weight = 1
    contentDir = "content/fr"

    # Menu français
    [[languages.fr.menu.main]]
      name = "Accueil"
      pageRef = "/"
      weight = 1
      identifier = "home"

    [[languages.fr.menu.main]]
      name = "À propos"
      pageRef = "a-propos"
      weight = 10
      identifier = "about"

    [[languages.fr.menu.main]]
      name = "Films"
      pageRef = "films"
      weight = 20
      identifier = "films"

    [[languages.fr.menu.main]]
      name = "Production"
      pageRef = "production"
      weight = 30
      identifier = "production"

    [[languages.fr.menu.main]]
      name = "Journal"
      pageRef = "journal"
      weight = 40
      identifier = "journal"

  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"

    # Menu anglais
    [[languages.en.menu.main]]
      name = "Home"
      pageRef = "/"
      weight = 1
      identifier = "home"

    [[languages.en.menu.main]]
      name = "About"
      pageRef = "a-propos"
      weight = 10
      identifier = "about"

    [[languages.en.menu.main]]
      name = "Films"
      pageRef = "films"
      weight = 20
      identifier = "films"

    [[languages.en.menu.main]]
      name = "Production"
      pageRef = "production"
      weight = 30
      identifier = "production"

    [[languages.en.menu.main]]
      name = "Journal"
      pageRef = "journal"
      weight = 40
      identifier = "journal"

